#!/usr/bin/env sh
# Check that -exec modifies find's behavior appropraitely

TEMP=$(mktemp -d)
WORK=$(pwd)

touch ${TEMP}/A
touch ${TEMP}/B
touch ${TEMP}/C

# grep all files that contain "a" using -exec
echo a | cat - > ${TEMP}/A
echo b | cat - > ${TEMP}/B

./find ${TEMP} -exec grep -qs a {} \; > ${TEMP}/C
echo >> ${TEMP}/C

# check that -exec still works if it is part of a larger expression
./find ${TEMP} -type f -exec test -s {} \; -ctime 1 >> ${TEMP}/C

cat <<EOF | diff - ${TEMP}/C
${TEMP}/A

${TEMP}/A
${TEMP}/B
${TEMP}/C
EOF
status=$?

rm -rf ${TEMP}
exit ${status}
