#!/usr/bin/env sh
# Ensure -a prints files starting with '.' and not having -a makes ls ignore
#   those files.

TEMP=$(mktemp -d)
WORK=$(pwd)

cd ${TEMP}

touch .A
touch A

${WORK}/ls > A
echo >> A
${WORK}/ls -a >> A

cat <<EOF | diff A -
A

.
..
.A
A
EOF
status=$?

cd ${WORK}
rm -rf ${TEMP}

exit ${status}
