#!/usr/bin/env sh
# Ensures ls exists and has basic functionality

TEMP=$(mktemp -d)
WORK=$(pwd)

touch ${TEMP}/A

cd ${TEMP}
${WORK}/ls | grep -q 'A'
status=$?

cd ${WORK}
rm -rf ${TEMP}

exit ${status}
