#!/usr/bin/env sh
# Checks that ls works with multiple paths

TEMP=$(mktemp -d)
WORK=$(pwd)

mkdir ${TEMP}/A
mkdir ${TEMP}/B
mkdir ${TEMP}/C

touch ${TEMP}/A/a
touch ${TEMP}/B/b
touch ${TEMP}/C/c
touch ${TEMP}/d

# One path, multiple paths, and checking for path ordering
./ls ${TEMP}/A > ${TEMP}/d
echo >> ${TEMP}/d
./ls ${TEMP}/A ${TEMP}/B ${TEMP}/C >> ${TEMP}/d
echo >> ${TEMP}/d
./ls ${TEMP}/C ${TEMP}/B ${TEMP}/A >> ${TEMP}/d
echo >> ${TEMP}/d

# Ensuring -d works with multi path
./ls -d ${TEMP}/A ${TEMP}/B ${TEMP}/C >> ${TEMP}/d

cat <<EOF | diff ${TEMP}/d -
a

${TEMP}/A:
a

${TEMP}/B:
b

${TEMP}/C:
c

${TEMP}/C:
c

${TEMP}/B:
b

${TEMP}/A:
a

${TEMP}/A

${TEMP}/B

${TEMP}/C
EOF
status=$?

rm -rf ${TEMP}

exit ${status}
