#!/usr/bin/env sh
#

TEMP=$(mktemp -d)
WORK=$(pwd)

cd ${TEMP}

touch .a
touch a

${WORK}/ls > a
${WORK}/ls -a >> a
cd ${WORK}
${WORK}/ls ${TEMP} -a >> ${TEMP}/a
${WORK}/ls -a ${TEMP} >> ${TEMP}/a
cd ${TEMP}

cat <<EOF | diff a -
a
.
..
.a
a
.
..
.a
a
.
..
.a
a
EOF
status=$?

cd ${WORK}
rm -rf ${TEMP}

exit ${status}
