#!/usr/bin/env sh
# Checks to make sure ls considers cases lexigraphically (i.e. not all upercases
#   followed by all lowercases)

TEMP=$(mktemp -d)
WORK=$(pwd)

cd ${TEMP}

touch a
touch A
touch b
touch B

${WORK}/ls > A
cat <<EOF | diff A -
A
a
B
b
EOF

status=$?

cd ${WORK}
rm -rf ${TEMP}
exit ${status}
